[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache'
cbor_metadata = true

remappings = [
    'forge-std/=lib/forge-std/src',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'account-abstraction/=lib/account-abstraction/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]

