FROM python:3.12-slim
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y wamerican git
RUN apt-get install -y gcc libgmp-dev
COPY ./requirements.txt /
RUN pip3 install --default-timeout=100 -r requirements.txt
COPY ./offchain /

CMD [ "python", "-u", "./offchain.py" ]
