FROM python:3.8-slim
RUN apt update
RUN apt install -y wamerican git
RUN pip3 install --default-timeout=100 web3~=6.14 git+https://github.com/bobanetwork/jsonrpclib.git jsonrpcclient redis python-dotenv
COPY ./offchain /
COPY ./aa_utils /aa_utils
CMD [ "python", "-u", "./offchain.py" ]
