name: Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-images:
    name: Publish Images
    runs-on: ubuntu-latest
    outputs:
      rundler-hc: ${{ steps.packages.outputs.rundler-hc }}
      offchain-rpc: ${{ steps.packages.outputs.offchain-rpc }}

    steps:
      - name: Check out source code
        uses: actions/checkout/@v4
        with:
          fetch-depth: 0

  rundler-hc:
    name: Publish rundler-hc
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bobanetwork/rundler-hc
          tags: |
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  offchain-rpc:
    name: Publish offchain-rpc
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bobanetwork/offchain-rpc
          tags: |
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./hybrid-compute
          file: hybrid-compute/Dockerfile.offchain-rpc
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
